spring.application.name=service

spring.datasource.url=jdbc:mysql://127.0.0.1:3306/ltss?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=secret
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.type.preferred_uuid_jdbc_type=CHAR